name: Deploy Next.js site to Pages
on:
  push:
    branches: ["main"]  # Trigger deployment on push to the main branch
  workflow_dispatch:  # Allows manual execution of the workflow from the GitHub UI

permissions:
  contents: read  # Read access to the repository contents
  pages: write  # Write access to GitHub Pages to create/update deployments
  id-token: write  # Required for authentication with GitHub Pages deployment

concurrency:
  group: "pages"  # Groups deployments under the "pages" label
  cancel-in-progress: false  # Completes running deployments before starting new ones

jobs:
  build:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clones the repository code to the runner

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"  # Installs Node.js version 20.x on the runner

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8  # Installs pnpm package manager version 8
          run_install: false  # Doesn't automatically run installation yet

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT  # Identifies pnpm's global store location for caching

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}  # Caches pnpm dependencies for faster future builds
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}  # Cache key based on OS and lock file
          restore-keys: |
            ${{ runner.os }}-pnpm-store-  # Fallback cache key if exact match not found

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next  # Configures GitHub Pages specifically for Next.js static exports

      - name: Install dependencies
        run: pnpm install  # Installs all project dependencies defined in package.json

      - name: Setup Next.js cache
        uses: actions/cache@v4
        with:
          path: .next/cache  # Caches Next.js build artifacts
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml', '**.[jt]s', '**.[jt]sx') }}  # Cache key based on code files
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-  # Fallback cache keys
            ${{ runner.os }}-nextjs-

      - name: Build with Next.js
        run: pnpm next build  # Builds the Next.js project, creating static files in the ./out directory
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out  # Uploads the static site files as a deployment artifact

  deploy:
    environment:
      name: github-pages  # Specifies the GitHub Pages environment for deployment
      url: ${{ steps.deployment.outputs.page_url }}  # Sets the deployment URL from the deploy step's output

    runs-on: ubuntu-latest
    needs: build  # Makes this job wait for the build job to complete successfully first

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Deploys the uploaded artifact to GitHub Pages